name: 'Stencila Action'
description: 'Setup Stencila CLI in GitHub Actions workflows to lint, release, and push executable documents'
author: 'Stencila'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  version:
    description: 'Version of Stencila CLI to install (e.g., "latest", "2.0.0")'
    required: false
    default: 'latest'
  command:
    description: 'Stencila command to run (e.g., "lint", "release", "push")'
    required: false
  args:
    description: 'Arguments to pass to the Stencila command'
    required: false
  convert:
    description: 'Run "stencila convert" with these arguments'
    required: false
  lint:
    description: 'Run "stencila lint" with these arguments'
    required: false
  execute:
    description: 'Run "stencila execute" with these arguments'
    required: false
  render:
    description: 'Run "stencila render" with these arguments'
    required: false
  assets:
    description: 'Path pattern for assets files to store after each run (e.g., "*.pdf", "output/**/*")'
    required: false
  assets-name:
    description: 'Name for the uploaded assets artifact (if assets is specified)'
    required: false
    default: 'assets'
  releases:
    description: 'Enable releases on tags. Set to true to use assets pattern, or provide a custom pattern (e.g., "*.pdf")'
    required: false
    default: 'true'
  release-name:
    description: 'Jinja template string or path to document to be rendered by Stencila into release name (defaults to tag name)'
    required: false
  release-notes:
    description: 'Jinja template string or path to document to be rendered by Stencila into release notes'
    required: false
  working-directory:
    description: 'Working directory to run Stencila commands'
    required: false
    default: '.'
  cache:
    description: 'Whether to cache the .stencila folder between runs'
    required: false
    default: 'true'

outputs:
  version:
    description: 'The version of Stencila CLI that was installed'
  exit-code:
    description: 'Exit code from the Stencila command'

runs:
  using: 'node20'
  main: 'dist/index.js'