name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-multi-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Stencila on ${{ matrix.os }}
        uses: ./
        with:
          command: --version
        id: install

      - name: Verify installation
        run: stencila --version

      - name: Check output version
        run: echo "Installed version ${{ steps.install.outputs.version }}"

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test with specific version
        uses: ./
        with:
          version: 2.3.0
          command: --version

      - name: Test with working directory
        uses: ./
        with:
          working-directory: test
          command: --version

      - name: Test caching of .stencila directory
        uses: ./
        with:
          command: init

      - name: Test execution
        uses: ./
        with:
          execute: test/test.smd
