name: Test

on: [push, pull_request]

jobs:
  test-multi-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Stencila on ${{ matrix.os }}
        uses: ./
        with:
          command: --version
        id: install

      - name: Verify installation
        run: stencila --version

      - name: Check output version
        run: echo "Installed version ${{ steps.install.outputs.version }}"

      - name: Test caching of .stencila directory
        uses: ./
        with:
          command: init

  test-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    steps:
      - uses: actions/checkout@v4

      - name: Render test document
        uses: ./
        with:
          render: test.smd test.json test.md
          assets: test.*
          releases: test.*
          release-name: "{{ owner }}/{{ repo }} {{ tag }}"
          release-filenames: "{{ filestem }}-{{ datetime }}.{{ fileext }}"
          artifact-name: stored-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for creating releases

